### ISSUE TITLE
Fix `Callable[[TypeA], TypeB]` vs `Callable[TypeA, TypeB]` syntax

### ISSUE THREAD

**Issue by eliegoudout** [eliegoudout/las-vegas#1]
Even though `Callable[TypeA, TypeB]` is correctly interpreted as `Callable[[TypeA], TypeB]`, it's not mandatory. Syntax should be fixed in all project.
Discussion [here](https://github.com/python/typing/discussions/1344).

**Comment by csongorpilinszkinagy** [comment]
Newbie question: do you mean to change like two lines of code?

**Comment by eliegoudout** [comment]
Hello,

I didn't check but indeed it should be pretty fast. A simple search through all three files for `Callable` will give you the instances to check.

I purposefully left this open in case someone wanted to get involved with their first issue!

Feel free to do it :)
